spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/hibertest
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8099